anchor_version = "0.16.1"
solana_version = "1.8.16"

[workspace]
members = ["token-swap/program", "libraries/math", "token/program"]

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
spl_token_swap = "PSwapMdSai8tjrEXcxFeQth87xC4rRsa4VA5mhGhXkP"
